import { create_crystal_reference_input } from "./types";

// Comprehensive seed data for 100+ commonly collected/sold crystals
// Data compiled from metaphysical sources - not medical claims

export const crystalSeedData: create_crystal_reference_input[] = [
  // QUARTZ FAMILY
  {
    id: "clear-quartz",
    name: "Clear Quartz",
    alternateNames: ["Rock Crystal", "Crystal Quartz", "Master Healer"],
    description: "Clear Quartz is known as the 'Master Healer' and is one of the most versatile crystals. It amplifies energy and intention, enhances psychic abilities, and can be programmed for any purpose. It's an essential crystal for any collection.",
    colors: ["clear", "white"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["point", "cluster", "sphere", "tower", "raw", "tumbled", "wand"],
    chakras: ["crown", "third_eye", "throat", "heart", "solar_plexus", "sacral", "root"],
    elements: ["spirit"],
    zodiacSigns: ["aries", "leo"],
    planetaryAssociation: "Sun",
    numerology: 4,
    primaryProperties: ["amplification", "clarity", "manifestation", "healing", "programmability"],
    emotionalUses: ["mental clarity", "focus", "emotional balance"],
    spiritualUses: ["meditation", "energy amplification", "spiritual growth", "programming intentions"],
    physicalAssociations: ["immune system", "energy levels", "metabolism"],
    cleansingMethods: ["moonlight", "sunlight", "water", "smoke", "sound", "earth"],
    chargingMethods: ["sunlight", "moonlight", "intention"],
    avoidMethods: [],
    careNotes: "Clear quartz is very hardy and can be cleansed with most methods.",
    localities: ["Brazil", "Arkansas USA", "Madagascar", "Alps"],
  },
  {
    id: "amethyst",
    name: "Amethyst",
    alternateNames: ["Chevron Amethyst", "Brandberg Amethyst", "Vera Cruz Amethyst"],
    description: "Amethyst is a powerful protective stone with a high spiritual vibration. It guards against psychic attack, transmuting negative energy into love. A natural tranquilizer, it relieves stress and strain, soothes irritability, and balances mood swings.",
    colors: ["purple"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["cluster", "point", "geode", "tumbled", "sphere", "tower", "raw"],
    chakras: ["third_eye", "crown"],
    elements: ["air", "water"],
    zodiacSigns: ["pisces", "virgo", "aquarius", "capricorn"],
    planetaryAssociation: "Jupiter",
    numerology: 3,
    primaryProperties: ["intuition", "calm", "spiritual awareness", "protection", "sobriety"],
    emotionalUses: ["anxiety relief", "stress reduction", "grief support", "addiction recovery"],
    spiritualUses: ["meditation", "psychic development", "dream work", "spiritual protection"],
    physicalAssociations: ["headaches", "sleep", "hormone balance", "tension relief"],
    cleansingMethods: ["moonlight", "smoke", "sound", "selenite"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["prolonged_sunlight"],
    careNotes: "Avoid prolonged sunlight exposure as it may cause color fading.",
    localities: ["Brazil", "Uruguay", "Zambia", "Madagascar", "Mexico"],
  },
  {
    id: "rose-quartz",
    name: "Rose Quartz",
    alternateNames: ["Pink Quartz", "Love Stone"],
    description: "Rose Quartz is the stone of unconditional love and infinite peace. It is the most important crystal for the heart and heart chakra, teaching the true essence of love. It purifies and opens the heart at all levels.",
    colors: ["pink"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["tumbled", "sphere", "heart", "raw", "tower", "palm_stone"],
    chakras: ["heart"],
    elements: ["water", "earth"],
    zodiacSigns: ["taurus", "libra", "scorpio"],
    planetaryAssociation: "Venus",
    numerology: 7,
    primaryProperties: ["unconditional love", "self-love", "compassion", "peace", "emotional healing"],
    emotionalUses: ["heartbreak healing", "self-worth", "forgiveness", "emotional release"],
    spiritualUses: ["attracting love", "deepening relationships", "heart opening"],
    physicalAssociations: ["heart", "circulation", "skin", "fertility"],
    cleansingMethods: ["moonlight", "water", "smoke", "sound"],
    chargingMethods: ["moonlight", "crystal_cluster"],
    avoidMethods: ["prolonged_sunlight"],
    careNotes: "Can fade in prolonged sunlight. Best charged under moonlight.",
    localities: ["Brazil", "Madagascar", "South Africa", "India"],
  },
  {
    id: "citrine",
    name: "Citrine",
    alternateNames: ["Merchant's Stone", "Success Stone"],
    description: "Citrine is a powerful cleanser and regenerator. Carrying the power of the sun, it is warming, energizing, and highly creative. One of the crystals that never needs cleansing, it absorbs, transmutes, dissipates, and grounds negative energy.",
    colors: ["yellow", "orange", "gold"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["point", "cluster", "tumbled", "sphere", "tower", "raw"],
    chakras: ["solar_plexus", "sacral", "root"],
    elements: ["fire"],
    zodiacSigns: ["gemini", "aries", "libra", "leo"],
    planetaryAssociation: "Sun",
    numerology: 6,
    primaryProperties: ["abundance", "manifestation", "personal power", "creativity", "joy"],
    emotionalUses: ["confidence boost", "optimism", "motivation", "overcoming depression"],
    spiritualUses: ["manifestation", "wealth attraction", "solar plexus activation"],
    physicalAssociations: ["digestion", "metabolism", "energy", "thyroid"],
    cleansingMethods: ["sunlight", "moonlight", "smoke"],
    chargingMethods: ["sunlight"],
    avoidMethods: [],
    careNotes: "Natural citrine is rare. Heat-treated amethyst is commonly sold as citrine.",
    localities: ["Brazil", "Congo", "Madagascar", "Russia"],
  },
  {
    id: "smoky-quartz",
    name: "Smoky Quartz",
    alternateNames: ["Morion", "Cairngorm"],
    description: "Smoky Quartz is one of the most efficient grounding and anchoring stones. It is a superb antidote to stress, assisting in tolerating difficult times with equanimity. It teaches one to leave behind anything that no longer serves.",
    colors: ["brown", "gray", "black"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["point", "cluster", "tumbled", "sphere", "tower", "raw"],
    chakras: ["root", "earth_star"],
    elements: ["earth"],
    zodiacSigns: ["scorpio", "sagittarius", "capricorn"],
    planetaryAssociation: "Saturn",
    numerology: 2,
    primaryProperties: ["grounding", "protection", "stress relief", "transmutation", "detoxification"],
    emotionalUses: ["anxiety relief", "letting go", "fear dissolution", "emotional calm"],
    spiritualUses: ["grounding meditation", "releasing negativity", "shamanic work"],
    physicalAssociations: ["detoxification", "radiation protection", "pain relief"],
    cleansingMethods: ["moonlight", "earth", "smoke", "sound"],
    chargingMethods: ["moonlight", "earth"],
    avoidMethods: ["prolonged_sunlight"],
    careNotes: "Very dark smoky quartz may be artificially irradiated.",
    localities: ["Brazil", "Scotland", "Switzerland", "Australia"],
  },

  // BLACK STONES
  {
    id: "black-tourmaline",
    name: "Black Tourmaline",
    alternateNames: ["Schorl"],
    description: "Black Tourmaline is the most powerful protection stone. It creates a psychic shield deflecting and dispelling negative energies, entities, or destructive forces. It guards against radiation and environmental pollutants.",
    colors: ["black"],
    crystalSystem: "hexagonal",
    mohsHardness: 7.5,
    commonForms: ["raw", "tumbled", "point", "tower", "wand"],
    chakras: ["root", "earth_star"],
    elements: ["earth"],
    zodiacSigns: ["capricorn", "scorpio"],
    planetaryAssociation: "Saturn",
    numerology: 3,
    primaryProperties: ["protection", "grounding", "EMF protection", "purification", "security"],
    emotionalUses: ["anxiety relief", "fear release", "confidence", "security"],
    spiritualUses: ["psychic protection", "energy cleansing", "boundary setting"],
    physicalAssociations: ["immune system", "pain relief", "arthritis"],
    cleansingMethods: ["smoke", "sound", "earth", "moonlight"],
    chargingMethods: ["earth", "moonlight"],
    avoidMethods: ["water", "salt"],
    careNotes: "Avoid prolonged water exposure. Can be brittle.",
    localities: ["Brazil", "Africa", "Pakistan", "Maine USA"],
  },
  {
    id: "obsidian",
    name: "Obsidian",
    alternateNames: ["Volcanic Glass", "Apache Tears"],
    description: "Obsidian is molten lava that cooled so quickly it had no time to crystallize. It is a stone without boundaries or limitations. It works extremely fast with great power and requires careful handling.",
    colors: ["black"],
    crystalSystem: "amorphous",
    mohsHardness: 5.5,
    commonForms: ["raw", "sphere", "tumbled", "point", "skull", "freeform"],
    chakras: ["root"],
    elements: ["fire", "earth"],
    zodiacSigns: ["scorpio", "sagittarius"],
    planetaryAssociation: "Pluto",
    numerology: 1,
    primaryProperties: ["protection", "truth", "shadow work", "grounding", "psychic attack shield"],
    emotionalUses: ["releasing trauma", "facing truth", "emotional blockage clearing"],
    spiritualUses: ["scrying", "past life work", "shadow integration", "cord cutting"],
    physicalAssociations: ["digestion", "detoxification", "circulation"],
    cleansingMethods: ["smoke", "moonlight", "earth", "sound"],
    chargingMethods: ["moonlight", "earth"],
    avoidMethods: ["sunlight", "water"],
    careNotes: "Very sharp when fractured. Handle with care.",
    localities: ["Mexico", "USA", "Japan", "Iceland"],
  },
  {
    id: "black-onyx",
    name: "Black Onyx",
    alternateNames: ["Onyx"],
    description: "Black Onyx is a powerful protection stone that absorbs and transforms negative energy. It helps to prevent the drain of personal energy and aids the development of emotional and physical strength and stamina.",
    colors: ["black"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["tumbled", "sphere", "cabochon", "jewelry", "palm_stone"],
    chakras: ["root"],
    elements: ["earth"],
    zodiacSigns: ["leo", "capricorn"],
    planetaryAssociation: "Saturn",
    numerology: 6,
    primaryProperties: ["protection", "strength", "stamina", "self-control", "decision making"],
    emotionalUses: ["grief support", "self-confidence", "centering"],
    spiritualUses: ["grounding", "past life work", "banishing negativity"],
    physicalAssociations: ["bones", "teeth", "feet"],
    cleansingMethods: ["smoke", "moonlight", "sound"],
    chargingMethods: ["moonlight", "earth"],
    avoidMethods: [],
    careNotes: "Dyed onyx is common in the market.",
    localities: ["Brazil", "India", "Madagascar", "Uruguay"],
  },

  // LABRADORITE & MOONSTONE FAMILY
  {
    id: "labradorite",
    name: "Labradorite",
    alternateNames: ["Spectrolite", "Rainbow Moonstone"],
    description: "Labradorite is a stone of transformation and magic. It prepares the body and soul for the ascension process, raising consciousness and deflecting unwanted energies from the aura. Its iridescent flash represents hidden truths.",
    colors: ["gray", "blue", "green", "gold", "iridescent"],
    crystalSystem: "triclinic",
    mohsHardness: 6.5,
    commonForms: ["raw", "tumbled", "sphere", "palm_stone", "freeform", "tower"],
    chakras: ["third_eye", "throat", "crown"],
    elements: ["water"],
    zodiacSigns: ["leo", "scorpio", "sagittarius"],
    planetaryAssociation: "Uranus",
    numerology: 6,
    primaryProperties: ["transformation", "intuition", "psychic protection", "magic", "self-discovery"],
    emotionalUses: ["anxiety reduction", "self-confidence", "inspiration"],
    spiritualUses: ["psychic development", "aura protection", "accessing akashic records"],
    physicalAssociations: ["eyes", "brain", "metabolism"],
    cleansingMethods: ["moonlight", "smoke", "sound", "selenite"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["salt", "prolonged_water"],
    careNotes: "Handle with care as it can chip along cleavage planes.",
    localities: ["Madagascar", "Finland", "Canada", "Mexico"],
  },
  {
    id: "moonstone",
    name: "Moonstone",
    alternateNames: ["Rainbow Moonstone", "White Moonstone", "Adularia"],
    description: "Moonstone is the stone of new beginnings. Strongly connected to the moon and to intuition, it is a stone for 'feeling' rather than thinking. It makes conscious the unconscious and promotes intuition and empathy.",
    colors: ["white", "clear", "blue", "iridescent"],
    crystalSystem: "monoclinic",
    mohsHardness: 6,
    commonForms: ["tumbled", "cabochon", "sphere", "palm_stone", "jewelry"],
    chakras: ["crown", "third_eye", "sacral"],
    elements: ["water"],
    zodiacSigns: ["cancer", "libra", "scorpio"],
    planetaryAssociation: "Moon",
    numerology: 4,
    primaryProperties: ["intuition", "feminine energy", "new beginnings", "emotional balance", "fertility"],
    emotionalUses: ["emotional healing", "soothing emotions", "hormone balance"],
    spiritualUses: ["enhancing psychic gifts", "dream work", "goddess connection"],
    physicalAssociations: ["hormones", "fertility", "pregnancy", "menstrual cycle"],
    cleansingMethods: ["moonlight", "water", "selenite"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["sunlight", "salt"],
    careNotes: "Best charged during full moon. Fragile - handle with care.",
    localities: ["Sri Lanka", "India", "Madagascar", "Australia"],
  },

  // FLUORITE
  {
    id: "fluorite",
    name: "Fluorite",
    alternateNames: ["Fluorspar", "Rainbow Fluorite"],
    description: "Fluorite is highly protective on a psychic level, helping you discern external influences and shut off psychic manipulation. It cleanses and stabilizes the aura and is extremely effective against computer and electromagnetic stress.",
    colors: ["purple", "green", "blue", "clear", "yellow", "multicolor"],
    crystalSystem: "cubic",
    mohsHardness: 4,
    commonForms: ["raw", "cluster", "sphere", "tower", "pyramid", "tumbled"],
    chakras: ["third_eye", "heart", "throat"],
    elements: ["air", "water"],
    zodiacSigns: ["capricorn", "pisces"],
    planetaryAssociation: "Mercury",
    numerology: 7,
    primaryProperties: ["mental clarity", "focus", "learning", "protection", "organization"],
    emotionalUses: ["stress relief", "concentration", "decision making"],
    spiritualUses: ["meditation", "psychic development", "aura cleansing"],
    physicalAssociations: ["bones", "teeth", "brain function"],
    cleansingMethods: ["moonlight", "smoke", "sound", "selenite"],
    chargingMethods: ["moonlight", "crystal_cluster"],
    avoidMethods: ["water", "sunlight", "salt"],
    careNotes: "Soft and fragile. Avoid water and physical impacts.",
    localities: ["China", "Mexico", "Spain", "USA"],
  },

  // SELENITE
  {
    id: "selenite",
    name: "Selenite",
    alternateNames: ["Satin Spar", "Desert Rose", "Gypsum"],
    description: "Selenite is named after the Greek goddess of the moon, Selene. It has a very fine vibration and brings clarity of mind, opening the crown and higher chakras. It accesses angelic consciousness and higher guidance.",
    colors: ["white", "clear"],
    crystalSystem: "monoclinic",
    mohsHardness: 2,
    commonForms: ["wand", "tower", "raw", "palm_stone", "slice"],
    chakras: ["crown", "third_eye", "soul_star"],
    elements: ["air"],
    zodiacSigns: ["taurus", "cancer"],
    planetaryAssociation: "Moon",
    numerology: 8,
    primaryProperties: ["cleansing", "charging crystals", "clarity", "peace", "angel connection"],
    emotionalUses: ["calming", "clearing confusion", "peace"],
    spiritualUses: ["meditation", "cleansing other crystals", "angel communication", "accessing past lives"],
    physicalAssociations: ["spine alignment", "flexibility", "skin"],
    cleansingMethods: ["moonlight", "visualization", "sound"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["water"],
    careNotes: "NEVER put in water - it will dissolve. Very soft and fragile.",
    localities: ["Morocco", "Mexico", "USA", "Australia"],
  },

  // TIGER'S EYE FAMILY
  {
    id: "tigers-eye",
    name: "Tiger's Eye",
    alternateNames: ["Tiger Eye", "Cat's Eye Quartz"],
    description: "Tiger's Eye combines earth energy with sun energy to create a high vibrational state that is grounded yet spiritually uplifting. It enhances practical perception, brings prosperity, and protects against ill-wishing.",
    colors: ["brown", "gold", "yellow"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["tumbled", "sphere", "cabochon", "palm_stone", "jewelry"],
    chakras: ["solar_plexus", "sacral", "root"],
    elements: ["fire", "earth"],
    zodiacSigns: ["leo", "capricorn"],
    planetaryAssociation: "Sun",
    numerology: 4,
    primaryProperties: ["courage", "confidence", "protection", "prosperity", "grounding"],
    emotionalUses: ["self-worth", "motivation", "overcoming fear"],
    spiritualUses: ["manifestation", "grounded spiritual work", "psychic protection"],
    physicalAssociations: ["eyes", "throat", "digestion"],
    cleansingMethods: ["sunlight", "smoke", "sound"],
    chargingMethods: ["sunlight"],
    avoidMethods: [],
    careNotes: "One of the hardier stones. Can be cleansed in sunlight.",
    localities: ["South Africa", "Australia", "India", "Brazil"],
  },
  {
    id: "red-tigers-eye",
    name: "Red Tiger's Eye",
    alternateNames: ["Ox Eye", "Bull's Eye"],
    description: "Red Tiger's Eye is a stimulating stone that overcomes lethargy and provides motivation. It speeds up a slow metabolism and increases low sex drive. It is a survival stone that supports those in difficult situations.",
    colors: ["red", "brown"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["tumbled", "sphere", "cabochon", "palm_stone"],
    chakras: ["root", "sacral"],
    elements: ["fire", "earth"],
    zodiacSigns: ["leo", "capricorn"],
    planetaryAssociation: "Mars",
    numerology: 5,
    primaryProperties: ["motivation", "passion", "vitality", "protection", "courage"],
    emotionalUses: ["overcoming lethargy", "passion", "determination"],
    spiritualUses: ["kundalini activation", "grounding"],
    physicalAssociations: ["metabolism", "blood", "vitality"],
    cleansingMethods: ["sunlight", "smoke", "earth"],
    chargingMethods: ["sunlight", "earth"],
    avoidMethods: [],
    localities: ["South Africa", "Brazil", "India"],
  },
  {
    id: "blue-tigers-eye",
    name: "Blue Tiger's Eye",
    alternateNames: ["Hawk's Eye", "Falcon's Eye"],
    description: "Blue Tiger's Eye is calming and releases stress. It aids the overanxious, quick-tempered, and phobic. It slows metabolism, cools an overactive sex drive, and dissolves sexual frustrations.",
    colors: ["blue", "gray"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["tumbled", "sphere", "cabochon", "palm_stone"],
    chakras: ["throat", "third_eye"],
    elements: ["air", "earth"],
    zodiacSigns: ["capricorn", "leo"],
    planetaryAssociation: "Jupiter",
    numerology: 8,
    primaryProperties: ["calm", "communication", "insight", "focus", "patience"],
    emotionalUses: ["stress relief", "anxiety", "anger management"],
    spiritualUses: ["clairvoyance", "astral travel", "higher perspective"],
    physicalAssociations: ["throat", "thyroid", "eyes"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight"],
    avoidMethods: [],
    localities: ["South Africa", "India", "USA"],
  },

  // CARNELIAN
  {
    id: "carnelian",
    name: "Carnelian",
    alternateNames: ["Cornelian", "Red Agate"],
    description: "Carnelian restores vitality and motivation, and stimulates creativity. It gives courage, promotes positive life choices, dispels apathy, and motivates for success in business and other matters.",
    colors: ["orange", "red", "brown"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["tumbled", "palm_stone", "sphere", "jewelry", "raw"],
    chakras: ["sacral", "root"],
    elements: ["fire"],
    zodiacSigns: ["taurus", "cancer", "leo", "virgo"],
    planetaryAssociation: "Mars",
    numerology: 5,
    primaryProperties: ["creativity", "courage", "vitality", "motivation", "passion"],
    emotionalUses: ["overcoming abuse", "confidence", "positive choices"],
    spiritualUses: ["past life recall", "manifesting goals"],
    physicalAssociations: ["fertility", "lower back", "metabolism", "blood"],
    cleansingMethods: ["sunlight", "water", "smoke"],
    chargingMethods: ["sunlight"],
    avoidMethods: [],
    careNotes: "Dyed agate is often sold as carnelian. True carnelian has cloud-like internal patterns.",
    localities: ["Brazil", "India", "Uruguay", "Egypt"],
  },

  // LAPIS LAZULI
  {
    id: "lapis-lazuli",
    name: "Lapis Lazuli",
    alternateNames: ["Lapis", "Royal Blue Stone"],
    description: "Lapis Lazuli opens the third eye and balances the throat chakra. It is a stone of truth, encouraging honesty in the spoken and written word. It reveals inner truth and encourages self-awareness.",
    colors: ["blue", "gold"],
    crystalSystem: "cubic",
    mohsHardness: 5.5,
    commonForms: ["tumbled", "sphere", "cabochon", "jewelry", "raw", "palm_stone"],
    chakras: ["third_eye", "throat"],
    elements: ["water"],
    zodiacSigns: ["sagittarius", "libra", "virgo"],
    planetaryAssociation: "Jupiter",
    numerology: 3,
    primaryProperties: ["truth", "wisdom", "intuition", "self-awareness", "communication"],
    emotionalUses: ["self-expression", "releasing repressed anger", "honesty"],
    spiritualUses: ["meditation", "psychic abilities", "past life recall", "spiritual journeying"],
    physicalAssociations: ["throat", "thyroid", "hearing", "immune system"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["water", "salt"],
    careNotes: "Contains pyrite (gold flecks). Avoid water and chemicals.",
    localities: ["Afghanistan", "Chile", "Russia", "Pakistan"],
  },

  // MALACHITE
  {
    id: "malachite",
    name: "Malachite",
    alternateNames: ["Copper Green"],
    description: "Malachite is a powerful stone for transformation. It absorbs negative energies and pollutants, picking them up from the atmosphere and the body. It guards against radiation and clears electromagnetic pollution.",
    colors: ["green"],
    crystalSystem: "monoclinic",
    mohsHardness: 4,
    commonForms: ["tumbled", "sphere", "cabochon", "raw", "slice"],
    chakras: ["heart", "solar_plexus"],
    elements: ["earth"],
    zodiacSigns: ["scorpio", "capricorn"],
    planetaryAssociation: "Venus",
    numerology: 9,
    primaryProperties: ["transformation", "protection", "heart healing", "emotional clearing", "manifestation"],
    emotionalUses: ["releasing trauma", "breaking patterns", "emotional risk-taking"],
    spiritualUses: ["psychic protection", "accessing other realms", "manifestation"],
    physicalAssociations: ["liver", "immune system", "arthritis", "cramps"],
    cleansingMethods: ["smoke", "selenite", "sound"],
    chargingMethods: ["moonlight", "earth"],
    avoidMethods: ["water", "salt"],
    careNotes: "TOXIC when raw - do not make elixirs or ingest. Wash hands after handling raw pieces.",
    localities: ["Congo", "Zambia", "Russia", "Australia"],
  },

  // PYRITE
  {
    id: "pyrite",
    name: "Pyrite",
    alternateNames: ["Fool's Gold", "Iron Pyrite"],
    description: "Pyrite is an excellent energy shield. It blocks out negative energy and pollutants at all levels including infectious diseases. It promotes physical health and emotional well-being.",
    colors: ["gold"],
    crystalSystem: "cubic",
    mohsHardness: 6.5,
    commonForms: ["raw", "cluster", "cube", "sphere", "tumbled"],
    chakras: ["solar_plexus"],
    elements: ["fire", "earth"],
    zodiacSigns: ["leo"],
    planetaryAssociation: "Mars",
    numerology: 3,
    primaryProperties: ["abundance", "protection", "willpower", "confidence", "vitality"],
    emotionalUses: ["overcoming fear", "assertiveness", "ambition"],
    spiritualUses: ["manifestation", "solar plexus activation", "shielding"],
    physicalAssociations: ["bones", "blood", "lungs", "infections"],
    cleansingMethods: ["smoke", "sound", "sunlight"],
    chargingMethods: ["sunlight"],
    avoidMethods: ["water"],
    careNotes: "Will rust in water. Contains sulfur - wash hands after handling.",
    localities: ["Spain", "Peru", "Italy", "USA"],
  },

  // AMAZONITE
  {
    id: "amazonite",
    name: "Amazonite",
    alternateNames: ["Amazon Stone", "Amazon Jade"],
    description: "Amazonite is a soothing stone that calms the brain and nervous system. It helps you see both sides of a problem and balances masculine and feminine energies. It is an excellent filter for geopathic stress.",
    colors: ["green", "blue"],
    crystalSystem: "triclinic",
    mohsHardness: 6,
    commonForms: ["tumbled", "raw", "sphere", "palm_stone", "tower"],
    chakras: ["heart", "throat"],
    elements: ["water", "earth"],
    zodiacSigns: ["virgo", "aquarius"],
    planetaryAssociation: "Uranus",
    numerology: 5,
    primaryProperties: ["truth", "communication", "harmony", "soothing", "hope"],
    emotionalUses: ["calming", "dispelling worry", "seeing other perspectives"],
    spiritualUses: ["manifesting universal love", "throat chakra activation"],
    physicalAssociations: ["nervous system", "metabolism", "calcium"],
    cleansingMethods: ["moonlight", "smoke", "sound", "water"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["salt"],
    localities: ["Russia", "USA", "Brazil", "Madagascar"],
  },

  // RHODONITE
  {
    id: "rhodonite",
    name: "Rhodonite",
    alternateNames: ["Pink Manganese"],
    description: "Rhodonite is an emotional balancer that nurtures love and encourages the brotherhood of humanity. It is a useful first aid stone for healing emotional shock and panic. It clears away emotional wounds and scars.",
    colors: ["pink", "black"],
    crystalSystem: "triclinic",
    mohsHardness: 6,
    commonForms: ["tumbled", "palm_stone", "sphere", "raw", "jewelry"],
    chakras: ["heart", "root"],
    elements: ["earth", "fire"],
    zodiacSigns: ["taurus", "scorpio"],
    planetaryAssociation: "Mars",
    numerology: 9,
    primaryProperties: ["emotional healing", "forgiveness", "compassion", "self-love", "generosity"],
    emotionalUses: ["panic relief", "heartbreak healing", "emotional wounds"],
    spiritualUses: ["past life healing", "clearing karma", "soul retrieval"],
    physicalAssociations: ["heart", "wounds", "arthritis", "emphysema"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["salt"],
    localities: ["Russia", "Australia", "Brazil", "Madagascar"],
  },

  // HEMATITE
  {
    id: "hematite",
    name: "Hematite",
    alternateNames: ["Iron Rose", "Bloodstone"],
    description: "Hematite is particularly effective at grounding and protecting. It harmonizes mind, body, and spirit. It dissolves negativity and prevents negative energies from entering the aura.",
    colors: ["gray", "black", "silver"],
    crystalSystem: "hexagonal",
    mohsHardness: 6,
    commonForms: ["tumbled", "sphere", "jewelry", "raw", "palm_stone"],
    chakras: ["root", "earth_star"],
    elements: ["earth", "fire"],
    zodiacSigns: ["aries", "aquarius"],
    planetaryAssociation: "Mars",
    numerology: 9,
    primaryProperties: ["grounding", "protection", "courage", "strength", "focus"],
    emotionalUses: ["confidence", "willpower", "overcoming compulsions"],
    spiritualUses: ["grounding after spiritual work", "aura protection"],
    physicalAssociations: ["blood", "circulation", "iron absorption", "anemia"],
    cleansingMethods: ["smoke", "sound", "moonlight"],
    chargingMethods: ["earth", "moonlight"],
    avoidMethods: ["water"],
    careNotes: "Will rust in water. Magnetic hematite is synthetic.",
    localities: ["Brazil", "England", "USA", "Canada"],
  },

  // JASPER FAMILY
  {
    id: "red-jasper",
    name: "Red Jasper",
    alternateNames: ["Stone of Endurance"],
    description: "Red Jasper is the supreme nurturer. It sustains and supports during times of stress and brings tranquility and wholeness. It gently stimulates, helping to ground energy and rectify unjust situations.",
    colors: ["red", "brown"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["tumbled", "palm_stone", "sphere", "raw", "jewelry"],
    chakras: ["root", "sacral"],
    elements: ["fire", "earth"],
    zodiacSigns: ["aries", "scorpio"],
    planetaryAssociation: "Mars",
    numerology: 6,
    primaryProperties: ["nurturing", "stamina", "grounding", "protection", "passion"],
    emotionalUses: ["dream recall", "emotional stability", "courage"],
    spiritualUses: ["grounding spiritual energy", "earth connection", "shamanic journeying"],
    physicalAssociations: ["circulation", "blood", "liver"],
    cleansingMethods: ["water", "smoke", "earth", "moonlight"],
    chargingMethods: ["earth", "sunlight"],
    avoidMethods: [],
    localities: ["Worldwide"],
  },
  {
    id: "picture-jasper",
    name: "Picture Jasper",
    alternateNames: ["Landscape Jasper"],
    description: "Picture Jasper brings comfort and alleviates fear. It is a stone of proportion and harmony. Said to contain a message from the past within its patterns, it is useful for meditation and creativity.",
    colors: ["brown", "multicolor"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["tumbled", "palm_stone", "cabochon", "jewelry"],
    chakras: ["root", "third_eye"],
    elements: ["earth"],
    zodiacSigns: ["leo", "capricorn"],
    numerology: 8,
    primaryProperties: ["earth connection", "creativity", "visualization", "comfort", "harmony"],
    emotionalUses: ["overcoming fear", "finding hidden thoughts"],
    spiritualUses: ["meditation", "journeying", "earth healing"],
    physicalAssociations: ["skin", "immune system", "kidneys"],
    cleansingMethods: ["water", "smoke", "earth"],
    chargingMethods: ["earth", "sunlight"],
    avoidMethods: [],
    localities: ["USA", "Brazil", "Egypt", "Australia"],
  },
  {
    id: "ocean-jasper",
    name: "Ocean Jasper",
    alternateNames: ["Orbicular Jasper", "Sea Jasper"],
    description: "Ocean Jasper is a stone of joy and high spirits. It aids in accepting responsibility, developing patience, and circulating life force in the body. Its circular patterns symbolize interconnectedness.",
    colors: ["green", "white", "pink", "multicolor"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["tumbled", "sphere", "palm_stone", "freeform"],
    chakras: ["heart", "solar_plexus", "throat"],
    elements: ["water", "earth"],
    zodiacSigns: ["capricorn"],
    numerology: 6,
    primaryProperties: ["joy", "renewal", "patience", "responsibility", "positive outlook"],
    emotionalUses: ["uplifting mood", "releasing negativity", "self-love"],
    spiritualUses: ["heart opening", "connecting to nature", "service to others"],
    physicalAssociations: ["digestion", "thyroid", "circulation"],
    cleansingMethods: ["water", "smoke", "moonlight"],
    chargingMethods: ["moonlight", "earth"],
    avoidMethods: [],
    careNotes: "Only found in Madagascar, now the main deposit is underwater.",
    localities: ["Madagascar"],
  },

  // GREEN STONES
  {
    id: "green-aventurine",
    name: "Green Aventurine",
    alternateNames: ["Stone of Opportunity", "Aventurine"],
    description: "Green Aventurine is the stone of prosperity. It reinforces leadership qualities and decisiveness. It promotes compassion and empathy and encourages perseverance. It defuses negative situations.",
    colors: ["green"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["tumbled", "sphere", "palm_stone", "raw", "jewelry"],
    chakras: ["heart"],
    elements: ["earth", "water"],
    zodiacSigns: ["aries", "leo"],
    planetaryAssociation: "Mercury",
    numerology: 3,
    primaryProperties: ["luck", "prosperity", "opportunity", "confidence", "heart healing"],
    emotionalUses: ["calming anger", "releasing old patterns", "compassion"],
    spiritualUses: ["manifestation", "connecting with nature spirits"],
    physicalAssociations: ["heart", "skin", "allergies", "adrenals"],
    cleansingMethods: ["water", "smoke", "moonlight", "sunlight"],
    chargingMethods: ["sunlight", "earth"],
    avoidMethods: [],
    localities: ["India", "Brazil", "China", "Russia"],
  },
  {
    id: "jade",
    name: "Jade",
    alternateNames: ["Nephrite", "Jadeite", "Imperial Jade"],
    description: "Jade is the stone of serenity and purity. It signifies wisdom gathered in tranquility. It is a protective stone that keeps the wearer from harm and brings harmony. It attracts good luck and friendship.",
    colors: ["green", "white"],
    crystalSystem: "monoclinic",
    mohsHardness: 6.5,
    commonForms: ["tumbled", "cabochon", "jewelry", "carving", "palm_stone"],
    chakras: ["heart"],
    elements: ["earth", "water"],
    zodiacSigns: ["aries", "taurus", "gemini", "libra"],
    planetaryAssociation: "Venus",
    numerology: 5,
    primaryProperties: ["harmony", "prosperity", "longevity", "wisdom", "protection"],
    emotionalUses: ["emotional release", "calming", "self-sufficiency"],
    spiritualUses: ["dream work", "accessing spiritual realms", "shamanic journeying"],
    physicalAssociations: ["kidneys", "heart", "fertility", "longevity"],
    cleansingMethods: ["water", "moonlight", "smoke"],
    chargingMethods: ["moonlight", "earth"],
    avoidMethods: [],
    careNotes: "Jadeite is more valuable than nephrite. Both are true jade.",
    localities: ["Myanmar", "China", "Guatemala", "Russia"],
  },
  {
    id: "moss-agate",
    name: "Moss Agate",
    alternateNames: ["Mocha Stone"],
    description: "Moss Agate is a stabilizing stone strongly connected with nature. It is said to refresh the soul and enable you to see the beauty in all you behold. It is helpful in reducing sensitivity to weather and environmental pollutants.",
    colors: ["green", "clear", "white"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["tumbled", "raw", "sphere", "palm_stone", "jewelry"],
    chakras: ["heart"],
    elements: ["earth"],
    zodiacSigns: ["virgo", "gemini"],
    planetaryAssociation: "Mercury",
    numerology: 1,
    primaryProperties: ["abundance", "new beginnings", "nature connection", "grounding", "stability"],
    emotionalUses: ["self-expression", "releasing fear", "hope"],
    spiritualUses: ["connecting with nature spirits", "gardening magic"],
    physicalAssociations: ["immune system", "inflammation", "lymphatic system"],
    cleansingMethods: ["water", "earth", "smoke", "moonlight"],
    chargingMethods: ["earth", "moonlight"],
    avoidMethods: [],
    localities: ["USA", "India", "Brazil", "Uruguay"],
  },
  {
    id: "peridot",
    name: "Peridot",
    alternateNames: ["Chrysolite", "Olivine", "Evening Emerald"],
    description: "Peridot is a powerful cleanser that releases and neutralizes toxins on all levels. It alleviates jealousy, resentment, and spite, and reduces stress. It sharpens the mind and opens it to new levels of awareness.",
    colors: ["green", "yellow"],
    crystalSystem: "orthorhombic",
    mohsHardness: 6.5,
    commonForms: ["raw", "faceted", "jewelry", "tumbled"],
    chakras: ["heart", "solar_plexus"],
    elements: ["earth"],
    zodiacSigns: ["virgo", "leo", "scorpio", "sagittarius"],
    planetaryAssociation: "Sun",
    numerology: 6,
    primaryProperties: ["abundance", "prosperity", "happiness", "protection", "healing"],
    emotionalUses: ["releasing negative emotions", "jealousy", "forgiveness"],
    spiritualUses: ["connecting with nature", "abundance manifestation"],
    physicalAssociations: ["heart", "lungs", "gallbladder", "spleen"],
    cleansingMethods: ["water", "moonlight", "smoke"],
    chargingMethods: ["sunlight"],
    avoidMethods: ["salt"],
    careNotes: "Avoid sudden temperature changes. Can be heat-sensitive.",
    localities: ["Egypt", "Pakistan", "USA", "China"],
  },

  // SODALITE
  {
    id: "sodalite",
    name: "Sodalite",
    alternateNames: ["Poor Man's Lapis"],
    description: "Sodalite brings emotional balance and calms panic attacks. It enhances self-esteem, self-acceptance, and self-trust. It unites logic with intuition and opens spiritual perception.",
    colors: ["blue", "white"],
    crystalSystem: "cubic",
    mohsHardness: 5.5,
    commonForms: ["tumbled", "sphere", "palm_stone", "raw", "jewelry"],
    chakras: ["third_eye", "throat"],
    elements: ["water", "air"],
    zodiacSigns: ["sagittarius", "virgo"],
    planetaryAssociation: "Venus",
    numerology: 4,
    primaryProperties: ["truth", "logic", "intuition", "calm", "self-expression"],
    emotionalUses: ["panic attacks", "phobias", "guilt release"],
    spiritualUses: ["meditation", "accessing subconscious", "third eye activation"],
    physicalAssociations: ["throat", "vocal cords", "blood pressure", "metabolism"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["water", "salt"],
    localities: ["Brazil", "Canada", "Namibia", "Russia"],
  },

  // TURQUOISE
  {
    id: "turquoise",
    name: "Turquoise",
    alternateNames: ["Sky Stone"],
    description: "Turquoise is the most efficient healer, providing solace for the spirit and well-being for the body. It is a protective stone that has been used for amulets since time immemorial. It is a promoter of self-realization.",
    colors: ["blue", "green"],
    crystalSystem: "triclinic",
    mohsHardness: 6,
    commonForms: ["tumbled", "cabochon", "jewelry", "raw"],
    chakras: ["throat", "third_eye"],
    elements: ["earth", "air", "fire"],
    zodiacSigns: ["scorpio", "sagittarius", "pisces"],
    planetaryAssociation: "Jupiter",
    numerology: 1,
    primaryProperties: ["protection", "healing", "communication", "friendship", "purification"],
    emotionalUses: ["calming", "mood stabilizer", "romantic love"],
    spiritualUses: ["shamanic journeying", "past life recall", "spiritual attunement"],
    physicalAssociations: ["throat", "respiratory", "immune system", "anti-inflammatory"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["water", "sunlight", "chemicals"],
    careNotes: "Porous stone - avoid water, oils, perfumes. Much turquoise is stabilized or dyed.",
    localities: ["Iran", "USA", "China", "Egypt", "Mexico"],
  },

  // KYANITE
  {
    id: "blue-kyanite",
    name: "Blue Kyanite",
    alternateNames: ["Kyanite", "Disthene"],
    description: "Blue Kyanite is excellent for attunement and meditation. It is a powerful transmitter and amplifier of high frequency energies. It never needs cleansing as it does not hold negativity.",
    colors: ["blue"],
    crystalSystem: "triclinic",
    mohsHardness: 5.5,
    commonForms: ["raw", "wand", "blade"],
    chakras: ["throat", "third_eye"],
    elements: ["air"],
    zodiacSigns: ["aries", "taurus", "libra"],
    planetaryAssociation: "Jupiter",
    numerology: 4,
    primaryProperties: ["alignment", "attunement", "communication", "meditation", "energy transfer"],
    emotionalUses: ["calming", "perseverance", "reason"],
    spiritualUses: ["chakra alignment", "dream recall", "past life access"],
    physicalAssociations: ["throat", "voice", "brain", "muscular system"],
    cleansingMethods: ["smoke", "sound", "moonlight"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["water"],
    careNotes: "Very different hardness along different axes. Handle carefully.",
    localities: ["Brazil", "USA", "India", "Kenya"],
  },

  // HOWLITE
  {
    id: "howlite",
    name: "Howlite",
    alternateNames: ["White Buffalo Stone"],
    description: "Howlite is an extremely calming stone. Placed under the pillow, it is an excellent antidote to insomnia. It links into the spiritual dimensions, opening attunement and preparing the mind to receive wisdom.",
    colors: ["white", "gray"],
    crystalSystem: "monoclinic",
    mohsHardness: 3.5,
    commonForms: ["tumbled", "sphere", "palm_stone", "raw"],
    chakras: ["crown", "third_eye"],
    elements: ["air"],
    zodiacSigns: ["gemini", "virgo"],
    numerology: 2,
    primaryProperties: ["calm", "patience", "sleep", "wisdom", "memory"],
    emotionalUses: ["reducing anxiety", "anger management", "patience"],
    spiritualUses: ["meditation", "accessing past lives", "dream work"],
    physicalAssociations: ["bones", "teeth", "calcium balance", "insomnia"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["water"],
    careNotes: "Often dyed to imitate turquoise. Soft stone.",
    localities: ["USA", "Canada", "Turkey"],
  },

  // LEPIDOLITE
  {
    id: "lepidolite",
    name: "Lepidolite",
    alternateNames: ["Lavender Stone", "Peace Stone"],
    description: "Lepidolite clears electromagnetic pollution and should be placed on computers. It dissipates negativity and insists on being used for the highest good. It activates and opens the throat, heart, third eye, and crown chakras.",
    colors: ["purple", "pink"],
    crystalSystem: "monoclinic",
    mohsHardness: 2.5,
    commonForms: ["raw", "tumbled", "palm_stone"],
    chakras: ["third_eye", "crown", "heart"],
    elements: ["water"],
    zodiacSigns: ["libra", "capricorn"],
    planetaryAssociation: "Jupiter",
    numerology: 8,
    primaryProperties: ["transition", "calm", "emotional balance", "stress relief", "EMF protection"],
    emotionalUses: ["anxiety", "depression", "mood swings", "addiction support"],
    spiritualUses: ["shamanic journeying", "accessing akashic records", "cosmic awareness"],
    physicalAssociations: ["nervous system", "joint pain", "menopause"],
    cleansingMethods: ["moonlight", "smoke", "sound", "selenite"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["water", "salt"],
    careNotes: "Contains lithium. Very soft - handle gently. Avoid water.",
    localities: ["Brazil", "Madagascar", "Russia", "USA"],
  },

  // AQUAMARINE
  {
    id: "aquamarine",
    name: "Aquamarine",
    alternateNames: ["Sea Water Stone"],
    description: "Aquamarine is a stone of courage. Its calming energies reduce stress and quiet the mind. It has an affinity with sensitive people and invokes tolerance. It overcomes judgmentalism and supports those overwhelmed by responsibility.",
    colors: ["blue", "clear"],
    crystalSystem: "hexagonal",
    mohsHardness: 7.5,
    commonForms: ["raw", "faceted", "jewelry", "tumbled", "tower"],
    chakras: ["throat", "heart"],
    elements: ["water"],
    zodiacSigns: ["aries", "gemini", "scorpio", "aquarius", "pisces"],
    planetaryAssociation: "Moon",
    numerology: 1,
    primaryProperties: ["courage", "calm", "communication", "tolerance", "truth"],
    emotionalUses: ["soothing fears", "calming anger", "stress reduction"],
    spiritualUses: ["meditation", "connecting with ocean energies", "prophetic visions"],
    physicalAssociations: ["throat", "thyroid", "hormones", "eyes"],
    cleansingMethods: ["water", "moonlight", "smoke"],
    chargingMethods: ["moonlight", "water"],
    avoidMethods: ["prolonged_sunlight"],
    localities: ["Brazil", "Pakistan", "Madagascar", "Russia"],
  },

  // GARNET
  {
    id: "garnet",
    name: "Garnet",
    alternateNames: ["Stone of Commitment", "Almandine", "Pyrope"],
    description: "Garnet is a powerfully energizing and regenerating stone. It cleanses and reenergizes the chakras. It inspires love and devotion, balances the sex drive, and alleviates emotional disharmony.",
    colors: ["red", "brown", "orange", "green"],
    crystalSystem: "cubic",
    mohsHardness: 7,
    commonForms: ["raw", "tumbled", "faceted", "jewelry"],
    chakras: ["root", "heart"],
    elements: ["fire", "earth"],
    zodiacSigns: ["aries", "leo", "virgo", "capricorn", "aquarius"],
    planetaryAssociation: "Mars",
    numerology: 2,
    primaryProperties: ["passion", "vitality", "regeneration", "love", "commitment"],
    emotionalUses: ["courage", "hope", "self-confidence"],
    spiritualUses: ["past life recall", "kundalini activation", "manifesting abundance"],
    physicalAssociations: ["blood", "heart", "metabolism", "regeneration"],
    cleansingMethods: ["water", "moonlight", "smoke", "earth"],
    chargingMethods: ["sunlight", "earth"],
    avoidMethods: [],
    localities: ["India", "Sri Lanka", "Brazil", "USA"],
  },

  // ANGELITE
  {
    id: "angelite",
    name: "Angelite",
    alternateNames: ["Blue Anhydrite", "Angel Stone"],
    description: "Angelite is formed from celestite that has been compressed over millions of years. It represents peace and brotherhood. It facilitates conscious contact with the angelic realm and enhances telepathic communication.",
    colors: ["blue", "white"],
    crystalSystem: "orthorhombic",
    mohsHardness: 3.5,
    commonForms: ["tumbled", "palm_stone", "sphere", "raw"],
    chakras: ["throat", "third_eye", "crown"],
    elements: ["air"],
    zodiacSigns: ["aquarius"],
    planetaryAssociation: "Uranus",
    numerology: 1,
    primaryProperties: ["angelic communication", "peace", "compassion", "truth", "tranquility"],
    emotionalUses: ["calming", "forgiveness", "acceptance"],
    spiritualUses: ["angel connection", "astral travel", "telepathy"],
    physicalAssociations: ["throat", "thyroid", "inflammation"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["water"],
    careNotes: "Will dissolve in water. Handle gently - soft stone.",
    localities: ["Peru", "Mexico", "Germany"],
  },

  // CELESTITE
  {
    id: "celestite",
    name: "Celestite",
    alternateNames: ["Celestine", "Sky Stone"],
    description: "Celestite has a high vibration and is a teacher for the New Age. It is imbued with divine energies and takes you into the infinite peace of the angelic realm. It jump-starts spiritual development.",
    colors: ["blue", "clear", "white"],
    crystalSystem: "orthorhombic",
    mohsHardness: 3.5,
    commonForms: ["cluster", "geode", "raw", "point"],
    chakras: ["throat", "third_eye", "crown"],
    elements: ["air"],
    zodiacSigns: ["gemini", "libra"],
    planetaryAssociation: "Neptune",
    numerology: 2,
    primaryProperties: ["divine connection", "peace", "angelic communication", "clarity", "higher consciousness"],
    emotionalUses: ["calming", "inner peace", "hope"],
    spiritualUses: ["meditation", "angel contact", "akashic records", "dream recall"],
    physicalAssociations: ["eyes", "ears", "mental clarity"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["water", "sunlight"],
    careNotes: "Very fragile. Fades in sunlight. Do not get wet.",
    localities: ["Madagascar", "Mexico", "USA", "Poland"],
  },

  // CHRYSOCOLLA
  {
    id: "chrysocolla",
    name: "Chrysocolla",
    alternateNames: ["Goddess Stone"],
    description: "Chrysocolla is a tranquil stone for use in meditation and communication. It draws off negative energies and calms, cleanses, and re-energizes all the chakras. It is a teaching stone encouraging us to reveal our highest knowledge.",
    colors: ["blue", "green"],
    crystalSystem: "monoclinic",
    mohsHardness: 2.5,
    commonForms: ["raw", "tumbled", "cabochon", "jewelry"],
    chakras: ["throat", "heart"],
    elements: ["water"],
    zodiacSigns: ["taurus", "gemini", "virgo"],
    planetaryAssociation: "Venus",
    numerology: 5,
    primaryProperties: ["communication", "empowerment", "teaching", "goddess energy", "tranquility"],
    emotionalUses: ["heartache", "guilt release", "self-awareness"],
    spiritualUses: ["meditation", "connecting with earth", "goddess connection"],
    physicalAssociations: ["throat", "thyroid", "arthritis", "blood"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight", "earth"],
    avoidMethods: ["water", "salt"],
    careNotes: "Very soft. Often stabilized with resin. Avoid water.",
    localities: ["Peru", "Congo", "USA", "Chile"],
  },

  // SUNSTONE
  {
    id: "sunstone",
    name: "Sunstone",
    alternateNames: ["Heliolite", "Viking Compass Stone"],
    description: "Sunstone is a joyful, light-inspiring stone. It instills good nature and heightens intuition. If life has lost its sweetness, sunstone will restore it and help you to nurture yourself.",
    colors: ["orange", "gold", "red"],
    crystalSystem: "triclinic",
    mohsHardness: 6.5,
    commonForms: ["tumbled", "cabochon", "jewelry", "raw"],
    chakras: ["sacral", "solar_plexus"],
    elements: ["fire"],
    zodiacSigns: ["leo", "libra"],
    planetaryAssociation: "Sun",
    numerology: 1,
    primaryProperties: ["joy", "vitality", "leadership", "freedom", "abundance"],
    emotionalUses: ["depression", "seasonal affective disorder", "self-worth"],
    spiritualUses: ["solar energy work", "manifestation", "finding your purpose"],
    physicalAssociations: ["metabolism", "digestion", "vitality", "throat"],
    cleansingMethods: ["sunlight", "smoke", "sound"],
    chargingMethods: ["sunlight"],
    avoidMethods: [],
    localities: ["India", "Norway", "USA", "Canada"],
  },

  // PREHNITE
  {
    id: "prehnite",
    name: "Prehnite",
    alternateNames: ["Stone of Prophecy"],
    description: "Prehnite is a stone of unconditional love and the crystal to heal the healer. It enhances precognition and inner knowing. It enables you to always be prepared, no matter what.",
    colors: ["green", "yellow"],
    crystalSystem: "orthorhombic",
    mohsHardness: 6.5,
    commonForms: ["tumbled", "raw", "sphere", "cabochon"],
    chakras: ["heart", "solar_plexus", "third_eye"],
    elements: ["earth", "water"],
    zodiacSigns: ["libra", "virgo"],
    planetaryAssociation: "Venus",
    numerology: 5,
    primaryProperties: ["unconditional love", "prophecy", "healing", "peace", "protection"],
    emotionalUses: ["releasing worry", "phobias", "nightmares"],
    spiritualUses: ["meditation", "visualization", "connecting with nature beings"],
    physicalAssociations: ["kidneys", "bladder", "thymus", "shoulders"],
    cleansingMethods: ["water", "moonlight", "smoke"],
    chargingMethods: ["moonlight", "earth"],
    avoidMethods: [],
    localities: ["South Africa", "Australia", "China", "USA"],
  },

  // UNAKITE
  {
    id: "unakite",
    name: "Unakite",
    alternateNames: ["Epidote Granite"],
    description: "Unakite is a stone of vision. It balances emotions with spirituality. It facilitates rebirthing, gently releasing conditions that inhibit spiritual and psychological growth. It is supportive in convalescence.",
    colors: ["green", "pink"],
    crystalSystem: "monoclinic",
    mohsHardness: 6.5,
    commonForms: ["tumbled", "palm_stone", "sphere", "raw"],
    chakras: ["heart", "third_eye"],
    elements: ["earth", "water"],
    zodiacSigns: ["scorpio"],
    numerology: 9,
    primaryProperties: ["balance", "rebirth", "patience", "persistence", "grounding spirituality"],
    emotionalUses: ["releasing old patterns", "self-love", "patience"],
    spiritualUses: ["past life healing", "scrying", "grounding spiritual growth"],
    physicalAssociations: ["reproductive system", "pregnancy", "convalescence"],
    cleansingMethods: ["water", "moonlight", "smoke", "earth"],
    chargingMethods: ["moonlight", "earth"],
    avoidMethods: [],
    localities: ["USA", "South Africa", "Brazil"],
  },

  // BLOODSTONE
  {
    id: "bloodstone",
    name: "Bloodstone",
    alternateNames: ["Heliotrope", "Blood Jasper"],
    description: "Bloodstone is an excellent blood cleanser and a powerful healer. It heightens intuition and increases creativity. It is grounding and protecting and draws off negative environmental energy.",
    colors: ["green", "red"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["tumbled", "palm_stone", "cabochon", "raw"],
    chakras: ["root", "heart"],
    elements: ["earth", "fire"],
    zodiacSigns: ["aries", "pisces", "libra"],
    planetaryAssociation: "Mars",
    numerology: 4,
    primaryProperties: ["vitality", "courage", "purification", "grounding", "protection"],
    emotionalUses: ["courage", "calming", "irritability reduction"],
    spiritualUses: ["past life healing", "ancestor connection", "dreaming"],
    physicalAssociations: ["blood", "circulation", "immune system", "detoxification"],
    cleansingMethods: ["water", "moonlight", "smoke", "earth"],
    chargingMethods: ["sunlight", "earth"],
    avoidMethods: [],
    localities: ["India", "Brazil", "Australia", "USA"],
  },

  // APATITE
  {
    id: "blue-apatite",
    name: "Blue Apatite",
    alternateNames: ["Apatite"],
    description: "Blue Apatite is a motivational stone promoting independence and ambitiousness. It is a stone of manifestation and is attuned to the future yet connects to past lives. It develops psychic gifts and spiritual attunement.",
    colors: ["blue"],
    crystalSystem: "hexagonal",
    mohsHardness: 5,
    commonForms: ["raw", "tumbled", "point", "tower"],
    chakras: ["third_eye", "throat"],
    elements: ["air", "water"],
    zodiacSigns: ["gemini", "libra"],
    planetaryAssociation: "Mercury",
    numerology: 9,
    primaryProperties: ["manifestation", "motivation", "clarity", "psychic activation", "communication"],
    emotionalUses: ["apathy", "anger", "frustration"],
    spiritualUses: ["past life access", "lucid dreaming", "psychic development"],
    physicalAssociations: ["bones", "teeth", "cartilage", "motor function"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["water", "salt"],
    careNotes: "Soft stone - handle with care. Avoid water and abrasives.",
    localities: ["Brazil", "Madagascar", "Russia", "Canada"],
  },

  // MOLDAVITE
  {
    id: "moldavite",
    name: "Moldavite",
    alternateNames: ["Bouteille Stone", "Vltavin"],
    description: "Moldavite is a rare tektite formed by a meteorite impact 15 million years ago. It has an extremely high vibration that opens, clears, and aligns the chakras. It is a catalyst for spiritual awakening and transformation.",
    colors: ["green"],
    crystalSystem: "amorphous",
    mohsHardness: 5.5,
    commonForms: ["raw", "freeform"],
    chakras: ["heart", "third_eye", "crown", "soul_star"],
    elements: ["fire", "spirit"],
    zodiacSigns: ["scorpio"],
    planetaryAssociation: "Uranus",
    numerology: 2,
    primaryProperties: ["transformation", "acceleration", "extraterrestrial connection", "rapid spiritual evolution", "interdimensional access"],
    emotionalUses: ["releasing old patterns", "rapid transformation"],
    spiritualUses: ["meditation", "channeling", "accessing higher dimensions", "star being connection"],
    physicalAssociations: ["eyes", "digestion", "sensitivity"],
    cleansingMethods: ["moonlight", "smoke", "sound", "clear_quartz"],
    chargingMethods: ["moonlight", "meditation"],
    avoidMethods: ["water"],
    careNotes: "Expensive and often faked. Buy from reputable sources. Can cause intense reactions.",
    localities: ["Czech Republic"],
  },

  // SHUNGITE
  {
    id: "shungite",
    name: "Shungite",
    alternateNames: ["Shungit"],
    description: "Shungite is an ancient stone believed to be almost 2 billion years old. It is a powerful purifier and protector. It is known for its ability to neutralize EMF radiation and purify water.",
    colors: ["black"],
    crystalSystem: "amorphous",
    mohsHardness: 3.5,
    commonForms: ["raw", "tumbled", "pyramid", "sphere", "jewelry"],
    chakras: ["root", "earth_star"],
    elements: ["earth", "fire"],
    zodiacSigns: ["scorpio", "capricorn", "cancer"],
    numerology: 4,
    primaryProperties: ["EMF protection", "purification", "grounding", "healing", "detoxification"],
    emotionalUses: ["stress relief", "anxiety reduction"],
    spiritualUses: ["grounding spiritual energy", "aura cleansing"],
    physicalAssociations: ["immune system", "inflammation", "water purification"],
    cleansingMethods: ["sunlight", "earth", "smoke"],
    chargingMethods: ["sunlight", "earth"],
    avoidMethods: [],
    careNotes: "Can leave black residue. Elite shungite (silver) is higher grade.",
    localities: ["Russia"],
  },

  // LARIMAR
  {
    id: "larimar",
    name: "Larimar",
    alternateNames: ["Dolphin Stone", "Atlantis Stone", "Stefilia's Stone"],
    description: "Larimar is a rare stone found only in the Dominican Republic. It connects with Atlantean energy and dolphin consciousness. It brings tranquility of sea and air to heart and mind.",
    colors: ["blue", "white"],
    crystalSystem: "triclinic",
    mohsHardness: 5,
    commonForms: ["cabochon", "jewelry", "palm_stone", "raw"],
    chakras: ["throat", "heart", "third_eye", "crown"],
    elements: ["water", "fire"],
    zodiacSigns: ["leo"],
    planetaryAssociation: "Neptune",
    numerology: 6,
    primaryProperties: ["serenity", "communication", "divine feminine", "cooling anger", "Atlantean connection"],
    emotionalUses: ["calming", "stress relief", "releasing emotional bonds"],
    spiritualUses: ["meditation", "connecting with dolphins", "past life recall", "Atlantean wisdom"],
    physicalAssociations: ["throat", "cartilage", "feet"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["sunlight", "salt"],
    careNotes: "Rare and can fade in sunlight. Only found in Dominican Republic.",
    localities: ["Dominican Republic"],
  },

  // CHAROITE
  {
    id: "charoite",
    name: "Charoite",
    alternateNames: ["Stone of Transformation"],
    description: "Charoite is a stone of transformation and is used to overcome fears. It stimulates inner vision and spiritual insight. It cleanses the aura and chakras by transmuting negative energy into healing.",
    colors: ["purple"],
    crystalSystem: "monoclinic",
    mohsHardness: 5,
    commonForms: ["tumbled", "cabochon", "palm_stone", "sphere"],
    chakras: ["heart", "third_eye", "crown"],
    elements: ["air"],
    zodiacSigns: ["scorpio", "sagittarius"],
    planetaryAssociation: "Pluto",
    numerology: 7,
    primaryProperties: ["transformation", "courage", "insight", "transmutation", "spiritual protection"],
    emotionalUses: ["overcoming fear", "obsessive thoughts", "acceptance"],
    spiritualUses: ["past life healing", "accessing spiritual guidance", "shamanic work"],
    physicalAssociations: ["nervous system", "eyes", "heart", "liver"],
    cleansingMethods: ["moonlight", "smoke", "sound", "selenite"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["water"],
    careNotes: "Only found in Russia. Can be expensive. Handle with care.",
    localities: ["Russia"],
  },

  // IOLITE
  {
    id: "iolite",
    name: "Iolite",
    alternateNames: ["Water Sapphire", "Viking Stone", "Cordierite"],
    description: "Iolite is a vision stone that clears thought forms, opening intuition. It aids in understanding and releasing the causes of addiction. It supports taking responsibility for yourself and overcoming codependency.",
    colors: ["blue", "purple"],
    crystalSystem: "orthorhombic",
    mohsHardness: 7,
    commonForms: ["faceted", "tumbled", "raw", "jewelry"],
    chakras: ["third_eye", "crown"],
    elements: ["water"],
    zodiacSigns: ["taurus", "libra", "sagittarius"],
    planetaryAssociation: "Saturn",
    numerology: 7,
    primaryProperties: ["vision", "intuition", "self-mastery", "creativity", "inner knowing"],
    emotionalUses: ["codependency", "addiction", "discord in relationships"],
    spiritualUses: ["shamanic journeying", "astral projection", "accessing inner vision"],
    physicalAssociations: ["eyes", "liver", "detoxification"],
    cleansingMethods: ["water", "moonlight", "smoke"],
    chargingMethods: ["moonlight"],
    avoidMethods: [],
    careNotes: "Shows different colors from different angles (pleochroism).",
    localities: ["India", "Sri Lanka", "Brazil", "Madagascar"],
  },

  // SPIRIT QUARTZ
  {
    id: "spirit-quartz",
    name: "Spirit Quartz",
    alternateNames: ["Cactus Quartz", "Fairy Quartz", "Pineapple Quartz"],
    description: "Spirit Quartz carries the vibration of universal love. It is a crystal of harmony and alignment. It radiates energy in all directions while the core amplifies intentions. It brings the gifts of the Spirit.",
    colors: ["purple", "white", "yellow"],
    crystalSystem: "hexagonal",
    mohsHardness: 7,
    commonForms: ["cluster", "point"],
    chakras: ["crown", "third_eye", "solar_plexus"],
    elements: ["spirit"],
    zodiacSigns: ["virgo", "capricorn", "aquarius", "pisces"],
    numerology: 5,
    primaryProperties: ["harmony", "unity", "spiritual evolution", "patience", "rebirth"],
    emotionalUses: ["grief", "group harmony", "patience"],
    spiritualUses: ["meditation", "astral travel", "multi-dimensional healing"],
    physicalAssociations: ["skin", "allergies", "detoxification"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight", "crystal_cluster"],
    avoidMethods: ["prolonged_sunlight"],
    careNotes: "Only found in South Africa. Delicate druzy crystals.",
    localities: ["South Africa"],
  },

  // BLACK KYANITE
  {
    id: "black-kyanite",
    name: "Black Kyanite",
    alternateNames: ["Witches Broom"],
    description: "Black Kyanite is a fan-shaped stone that clears energy from the entire auric field. It does not retain negative energy and never needs cleansing. It is an excellent grounding stone and assists in manifesting vision into reality.",
    colors: ["black"],
    crystalSystem: "triclinic",
    mohsHardness: 5.5,
    commonForms: ["raw", "blade", "fan"],
    chakras: ["root", "earth_star"],
    elements: ["earth"],
    zodiacSigns: ["aries", "libra"],
    numerology: 4,
    primaryProperties: ["grounding", "cord cutting", "energy clearing", "manifestation", "protection"],
    emotionalUses: ["releasing negativity", "clearing attachments"],
    spiritualUses: ["shamanic journeying", "past life healing", "earth healing"],
    physicalAssociations: ["adrenal glands", "muscles", "urogenital system"],
    cleansingMethods: ["smoke", "sound", "moonlight"],
    chargingMethods: ["earth", "moonlight"],
    avoidMethods: ["water"],
    careNotes: "Fragile - fans along one axis. Handle carefully.",
    localities: ["Brazil", "USA", "India"],
  },

  // APACHE TEARS
  {
    id: "apache-tears",
    name: "Apache Tears",
    alternateNames: ["Obsidian Nodules"],
    description: "Apache Tears are a form of black obsidian. They comfort grief and provide insight into the source of distress. They are gentler than other forms of obsidian and excellent for absorbing negative energy.",
    colors: ["black", "brown"],
    crystalSystem: "amorphous",
    mohsHardness: 5.5,
    commonForms: ["raw", "tumbled"],
    chakras: ["root"],
    elements: ["fire", "earth"],
    zodiacSigns: ["aries", "sagittarius"],
    planetaryAssociation: "Saturn",
    numerology: 1,
    primaryProperties: ["grief healing", "protection", "grounding", "forgiveness", "gentle truth"],
    emotionalUses: ["grief", "loss", "trauma", "emotional cleansing"],
    spiritualUses: ["grounding", "psychic protection", "gentle shadow work"],
    physicalAssociations: ["detoxification", "muscle spasms", "vitamin absorption"],
    cleansingMethods: ["smoke", "moonlight", "earth"],
    chargingMethods: ["moonlight", "earth"],
    avoidMethods: ["water"],
    careNotes: "Named for the tears of Apache women mourning lost warriors.",
    localities: ["USA"],
  },

  // ARAGONITE
  {
    id: "aragonite",
    name: "Aragonite",
    alternateNames: ["Sputnik Aragonite", "Aragonite Star Cluster"],
    description: "Aragonite is an earth healer and grounding stone. It transforms geopathic stress and clears blocked ley lines. It centers and grounds physical energies and is useful during stressful times.",
    colors: ["brown", "white", "yellow", "blue"],
    crystalSystem: "orthorhombic",
    mohsHardness: 3.5,
    commonForms: ["cluster", "raw", "tumbled"],
    chakras: ["root", "earth_star"],
    elements: ["earth"],
    zodiacSigns: ["capricorn"],
    planetaryAssociation: "Saturn",
    numerology: 9,
    primaryProperties: ["earth healing", "grounding", "centering", "patience", "concentration"],
    emotionalUses: ["stress relief", "anger management", "emotional stability"],
    spiritualUses: ["earth chakra activation", "connecting with earth", "past life recall"],
    physicalAssociations: ["bones", "calcium absorption", "warming extremities"],
    cleansingMethods: ["smoke", "sound", "moonlight"],
    chargingMethods: ["earth"],
    avoidMethods: ["water"],
    careNotes: "Soft and fragile. Avoid water and rough handling.",
    localities: ["Spain", "Morocco", "Namibia", "UK"],
  },

  // DANBURITE
  {
    id: "danburite",
    name: "Danburite",
    alternateNames: [],
    description: "Danburite is a highly spiritual stone carrying a pure vibration and working on the heart energy. It activates both the intellect and higher consciousness, linking into angelic realms. It promotes ease and changes recalcitrant attitudes.",
    colors: ["clear", "white", "pink", "yellow"],
    crystalSystem: "orthorhombic",
    mohsHardness: 7,
    commonForms: ["point", "raw", "tumbled"],
    chakras: ["heart", "crown", "soul_star"],
    elements: ["spirit"],
    zodiacSigns: ["leo"],
    planetaryAssociation: "Venus",
    numerology: 4,
    primaryProperties: ["angelic connection", "heart activation", "intellect", "emotional healing", "self-love"],
    emotionalUses: ["releasing grief", "comfort", "peace of mind"],
    spiritualUses: ["meditation", "lucid dreaming", "accessing higher dimensions"],
    physicalAssociations: ["liver", "gallbladder", "detoxification"],
    cleansingMethods: ["water", "moonlight", "smoke", "sunlight"],
    chargingMethods: ["moonlight", "sunlight"],
    avoidMethods: [],
    localities: ["Mexico", "Japan", "Russia", "USA"],
  },

  // RHODOCHROSITE
  {
    id: "rhodochrosite",
    name: "Rhodochrosite",
    alternateNames: ["Inca Rose", "Rosa del Inca"],
    description: "Rhodochrosite represents selfless love and compassion. It expands consciousness and integrates spiritual with material energies. It is an excellent stone for the heart and relationships, especially calling in a soulmate.",
    colors: ["pink", "red"],
    crystalSystem: "hexagonal",
    mohsHardness: 4,
    commonForms: ["raw", "tumbled", "slice", "sphere"],
    chakras: ["heart", "solar_plexus"],
    elements: ["fire", "water"],
    zodiacSigns: ["leo", "scorpio"],
    planetaryAssociation: "Venus",
    numerology: 4,
    primaryProperties: ["selfless love", "compassion", "soulmate attraction", "emotional healing", "self-worth"],
    emotionalUses: ["healing old wounds", "improving self-worth", "calling in love"],
    spiritualUses: ["meditation", "integrating spiritual and material", "soul retrieval"],
    physicalAssociations: ["heart", "blood pressure", "circulation", "kidneys"],
    cleansingMethods: ["moonlight", "smoke", "sound"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["water", "salt"],
    careNotes: "Soft and sensitive. Avoid water and rough handling. Can fade.",
    localities: ["Argentina", "USA", "Peru", "South Africa"],
  },

  // KUNZITE
  {
    id: "kunzite",
    name: "Kunzite",
    alternateNames: ["Pink Spodumene", "Evening Stone"],
    description: "Kunzite is a stone of emotion, opening and connecting the heart to the mind and stimulating a healing communion between the two. It encourages one to release walls built around the heart and to be receptive to unconditional love.",
    colors: ["pink", "purple", "clear"],
    crystalSystem: "monoclinic",
    mohsHardness: 6.5,
    commonForms: ["raw", "point", "faceted", "jewelry"],
    chakras: ["heart", "third_eye", "crown"],
    elements: ["water"],
    zodiacSigns: ["scorpio", "taurus", "leo"],
    planetaryAssociation: "Venus",
    numerology: 7,
    primaryProperties: ["unconditional love", "heart healing", "divine love", "peace", "centering"],
    emotionalUses: ["healing heartbreak", "releasing emotional debris", "connecting heart and mind"],
    spiritualUses: ["meditation", "connecting with divine love", "removing obstacles"],
    physicalAssociations: ["heart", "circulation", "lungs", "stress relief"],
    cleansingMethods: ["moonlight", "smoke", "sound", "selenite"],
    chargingMethods: ["moonlight"],
    avoidMethods: ["sunlight"],
    careNotes: "Fades in sunlight. Called 'Evening Stone' because best worn at night.",
    localities: ["Afghanistan", "Brazil", "Madagascar", "USA"],
  },
];

export default crystalSeedData;
