# Fetches secrets from Azure Key Vault and writes them to .env.build
# Usage: .\scripts\fetch-build-secrets.ps1 [-Env dev|prd]

param(
    [ValidateSet("dev", "prd")]
    [string]$Env = "dev"
)

$Suffix = "002"
$KvName = "kv-spv-server-$Env-$Suffix"
$FuncName = "func-spiriverse-server-$Env-$Suffix"
$RgServer = "rg-spiriverse-server-$Env-$Suffix"

Write-Host "Fetching secrets from $KvName..." -ForegroundColor Cyan

# Function app key
$FuncKey = az functionapp keys list --name $FuncName --resource-group $RgServer --query "functionKeys.client" -o tsv

# Key Vault secrets
$StripePk = az keyvault secret show --vault-name $KvName --name "stripe-pk" --query value -o tsv
$GoogleKey = az keyvault secret show --vault-name $KvName --name "google-key" --query value -o tsv
$NextAuthSecret = az keyvault secret show --vault-name $KvName --name "authjs-secret" --query value -o tsv
$StorageKey = az keyvault secret show --vault-name $KvName --name "storage-key" --query value -o tsv
$ConsoleTenantId = az keyvault secret show --vault-name $KvName --name "console-azure-ad-tenant-id" --query value -o tsv
$ConsoleClientId = az keyvault secret show --vault-name $KvName --name "console-azure-ad-client-id" --query value -o tsv
$ConsoleClientSecret = az keyvault secret show --vault-name $KvName --name "console-azure-ad-client-secret" --query value -o tsv
$ConsoleNextAuthSecret = az keyvault secret show --vault-name $KvName --name "console-nextauth-secret" --query value -o tsv

# Build the env file
$EnvFile = @"
# Auto-generated by fetch-build-secrets.ps1 - DO NOT COMMIT
# Environment: $Env

# Public build args
NEXT_PUBLIC_server_endpoint=https://$FuncName.azurewebsites.net/api
NEXT_PUBLIC_server_endpoint_code=$FuncKey
NEXT_PUBLIC_stripe_token=$StripePk
NEXT_PUBLIC_GOOGLE_KEY=$GoogleKey
NEXT_PUBLIC_STORAGE_ACCOUNT=stspvapp$Env$Suffix
NEXT_PUBLIC_graphql_proxy=http://localhost:3000/api/graphql
NEXT_PUBLIC_site_address=http://localhost:3000

# Auth secrets (needed at build time for NextAuth)
NEXTAUTH_SECRET=$NextAuthSecret
AUTH_AZURE_ACCESS_KEY=$StorageKey
CONSOLE_AZURE_AD_TENANT_ID=$ConsoleTenantId
CONSOLE_AZURE_AD_CLIENT_ID=$ConsoleClientId
CONSOLE_AZURE_AD_CLIENT_SECRET=$ConsoleClientSecret
CONSOLE_NEXTAUTH_SECRET=$ConsoleNextAuthSecret
"@

$OutputPath = Join-Path $PSScriptRoot ".." ".env.build"
$EnvFile | Out-File -FilePath $OutputPath -Encoding utf8NoBOM
Write-Host "Written to $OutputPath" -ForegroundColor Green
Write-Host ""
Write-Host "To build locally:" -ForegroundColor Yellow
Write-Host "  docker build --build-arg-file .env.build -t spiriverse-frontend ."
