"use client";
import { useState } from "react";
import { ArrowLeft, Plus, Edit2, Trash2, Save, X, List, Loader2 } from "lucide-react";
import UseFlatChoice from "./hooks/UseFlatChoice";
import UseUpsertFlatChoiceOption from "./hooks/UseUpsertFlatChoice";
import { choice_option_type, choice_config_type, Locale, RecordStatus } from "@/utils/spiriverse";
import { toast } from "sonner";

interface FlatChoiceEditorProps {
  config: choice_config_type;
  onBack: () => void;
}

export default function FlatChoiceEditor({ config, onBack }: FlatChoiceEditorProps) {
  const [editingOption, setEditingOption] = useState<choice_option_type | null>(null);
  const [isAddingNew, setIsAddingNew] = useState(false);
  const [newOption, setNewOption] = useState<{ defaultLabel: string; status: 'ACTIVE' | 'INACTIVE' }>({ defaultLabel: '', status: 'ACTIVE' });

  const { data: choice, isLoading, error } = UseFlatChoice(config.id);
  const upsertMutation = UseUpsertFlatChoiceOption();

  const handleAddNew = () => {
    setIsAddingNew(true);
    setNewOption({ defaultLabel: '', status: 'ACTIVE' });
  };

  const handleCancelAdd = () => {
    setIsAddingNew(false);
    setNewOption({ defaultLabel: '', status: 'ACTIVE' });
  };

  const handleSaveNew = () => {
    if (!choice?.id || !newOption.defaultLabel.trim()) return;

    const newOptionData: choice_option_type = {
      id: '', // Will be generated by backend
      defaultLabel: newOption.defaultLabel.trim(),
      localizations: [
        {
          locale: Locale.EN, // Replace 'en' with a valid Locale value as defined in your Locale type
          value: newOption.defaultLabel.trim()
        }
      ],
      status: newOption.status as RecordStatus,
    };

    upsertMutation.mutate({
      choiceId: choice.id,
      option: newOptionData
    }, {
      onSuccess: () => {
        toast.success('Option added successfully');
        setIsAddingNew(false);
        setNewOption({ defaultLabel: '', status: 'ACTIVE' });
      },
      onError: () => {
        toast.error('Failed to add option');
      }
    });
  };

  const handleEditOption = (option: choice_option_type) => {
    setEditingOption(option);
  };

  const handleCancelEdit = () => {
    setEditingOption(null);
  };

  const handleSaveEdit = () => {
    if (!choice?.id || !editingOption) return;

    upsertMutation.mutate({
      choiceId: choice.id,
      option: editingOption
    }, {
      onSuccess: () => {
        toast.success('Option updated successfully');
        setEditingOption(null);
      },
      onError: () => {
        toast.error('Failed to update option');
      }
    });
  };

  const handleDeleteOption = (optionId: string) => {
    // TODO: Implement delete option mutation
    console.log('Delete option:', optionId);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="flex items-center space-x-2 text-slate-400">
          <Loader2 className="h-5 w-5 animate-spin" />
          <span>Loading choice options...</span>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-6">
        <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-4">
          <p className="text-red-400">Failed to load choice options</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full min-h-0">
      {/* Header */}
      <div className="flex items-center justify-between p-6 border-b border-slate-800">
        <div className="flex items-center space-x-4">
          <button
            onClick={onBack}
            className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-lg transition-colors"
          >
            <ArrowLeft className="h-5 w-5" />
          </button>
          <div className="flex items-center space-x-3">
            <div className="h-10 w-10 bg-green-500/10 rounded-lg flex items-center justify-center">
              <List className="h-5 w-5 text-green-400" />
            </div>
            <div>
              <h1 className="text-xl font-semibold text-white">{config.label}</h1>
              <p className="text-sm text-slate-400">Flat choice list • {choice?.options?.length || 0} options</p>
            </div>
          </div>
        </div>

        <button
          onClick={handleAddNew}
          className="flex items-center space-x-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-colors"
        >
          <Plus className="h-4 w-4" />
          <span>Add Option</span>
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-6">
        <div className="max-w-4xl space-y-4">
          {/* Add New Option Form */}
          {isAddingNew && (
            <div className="bg-slate-800 border border-slate-700 rounded-lg p-4">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-white font-medium">Add New Option</h3>
                <button
                  onClick={handleCancelAdd}
                  className="p-1 text-slate-400 hover:text-white hover:bg-slate-700 rounded"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-2">
                    Label
                  </label>
                  <input
                    type="text"
                    value={newOption.defaultLabel}
                    onChange={(e) => setNewOption(prev => ({ ...prev, defaultLabel: e.target.value }))}
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                    placeholder="Enter option label"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-2">
                    Status
                  </label>
                  <select
                    value={newOption.status}
                    onChange={(e) => setNewOption(prev => ({ ...prev, status: e.target.value as 'ACTIVE' | 'INACTIVE' }))}
                    className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-white focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                  >
                    <option value="ACTIVE">Active</option>
                    <option value="INACTIVE">Inactive</option>
                  </select>
                </div>
                <div className="flex justify-end space-x-3">
                  <button
                    onClick={handleCancelAdd}
                    className="px-4 py-2 text-slate-400 hover:text-white transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleSaveNew}
                    disabled={!newOption.defaultLabel.trim() || upsertMutation.isPending}
                    className="flex items-center space-x-2 bg-green-600 hover:bg-green-700 disabled:bg-slate-700 disabled:text-slate-500 text-white px-4 py-2 rounded-lg transition-colors"
                  >
                    {upsertMutation.isPending ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Save className="h-4 w-4" />
                    )}
                    <span>{upsertMutation.isPending ? 'Saving...' : 'Save'}</span>
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Options List */}
          {choice?.options?.map((option) => (
            <div key={option.id} className="bg-slate-800 border border-slate-700 rounded-lg p-4">
              {editingOption?.id === option.id ? (
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-300 mb-2">
                      Label
                    </label>
                    <input
                      type="text"
                      value={editingOption.defaultLabel}
                      onChange={(e) => setEditingOption(prev => prev ? { ...prev, defaultLabel: e.target.value } : null)}
                      className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-300 mb-2">
                      Status
                    </label>
                    <select
                      value={editingOption.status}
                      onChange={(e) => setEditingOption(prev => prev ? { ...prev, status: e.target.value as typeof prev.status } : null)}
                      className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-white focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
                    >
                      <option value="ACTIVE">Active</option>
                      <option value="INACTIVE">Inactive</option>
                    </select>
                  </div>
                  <div className="flex justify-end space-x-3">
                    <button
                      onClick={handleCancelEdit}
                      className="px-4 py-2 text-slate-400 hover:text-white transition-colors"
                    >
                      Cancel
                    </button>
                    <button
                      onClick={handleSaveEdit}
                      disabled={upsertMutation.isPending}
                      className="flex items-center space-x-2 bg-green-600 hover:bg-green-700 disabled:bg-slate-700 disabled:text-slate-500 text-white px-4 py-2 rounded-lg transition-colors"
                    >
                      {upsertMutation.isPending ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                      ) : (
                        <Save className="h-4 w-4" />
                      )}
                      <span>{upsertMutation.isPending ? 'Saving...' : 'Save'}</span>
                    </button>
                  </div>
                </div>
              ) : (
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-4">
                    <div className="flex-1">
                      <h3 className="text-white font-medium">{option.defaultLabel}</h3>
                      <div className="flex items-center space-x-2 mt-1">
                        <span className={`text-xs px-2 py-0.5 rounded-full ${
                          option.status === 'ACTIVE'
                            ? 'bg-green-500/10 text-green-400'
                            : 'bg-gray-500/10 text-gray-400'
                        }`}>
                          {option.status}
                        </span>
                        <span className="text-xs text-slate-500">ID: {option.id}</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center space-x-2">
                    <button
                      onClick={() => handleEditOption(option)}
                      className="p-2 text-slate-400 hover:text-blue-400 hover:bg-slate-700 rounded-lg transition-colors"
                    >
                      <Edit2 className="h-4 w-4" />
                    </button>
                    <button
                      onClick={() => handleDeleteOption(option.id)}
                      className="p-2 text-slate-400 hover:text-red-400 hover:bg-slate-700 rounded-lg transition-colors"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                </div>
              )}
            </div>
          ))}

          {choice?.options?.length === 0 && (
            <div className="text-center py-12">
              <List className="h-12 w-12 text-slate-600 mx-auto mb-4" />
              <h3 className="text-lg font-medium text-white mb-2">No options yet</h3>
              <p className="text-slate-400 mb-4">Get started by adding your first option.</p>
              <button
                onClick={handleAddNew}
                className="flex items-center space-x-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-colors mx-auto"
              >
                <Plus className="h-4 w-4" />
                <span>Add First Option</span>
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}